multimer:
  peptide:
    gm-AE:
      mass: 698.2858
      mult_num: 2
    gm-AEJ:
      mass: 870.3704
      mult_num: 2
    gm-AEJA:
      mass: 941.4075
      mult_num: 2
    gm-AEJ=gm-AEJ:
      mass: 1722.7302
      mult_num: 3
    gm-AEJ=gm-AEJA:
      mass: 1793.7673
      mult_num: 3
    gm-AEJA=gm-AEJA:
      mass: 1864.8044
      mult_num: 3
  gycosidic:
    gm-AE:
      mass: 696.2702
      mult_num: 2
    gm-AEJ:
      mass: 868.3548
      mult_num: 2
    gm-AEJA:
      mass: 939.3919
      mult_num: 2
    gm-AEJ-gm-AEJ:
      mass: 1720.7146
      mult_num: 3
    gm-AEJ-gm-AEJA:
      mass: 1791.7517
      mult_num: 3
    gm-AEJA-gm-AEJA:
      mass: 1862.7888
      mult_num:  3
  lactyl:
    l-AE:
      mass: 290.1116
      mult_num: 2
    l-AEJ:
      mass: 462.1962
      mult_num: 2
    l-AEJA:
      mass: 533.2333
      mult_num: 2
    l-AEJ=l-AEJ:
      mass: 906.3818
      mult_num: 3
    l-AEJ=l-AEJA:
      mass: 977.4189
      mult_num: 3
    l-AEJA=l-AEJA:
      mass: 1048.4560
      mult_num: 3
mod_type:
  Anh:
    mass: -20.0262
    name:
  Double_Anh:
    mass: -40.0524
    name:
  DeAc:
    mass: -42.0105
    name:
  O-Acetylated:
    mass: 42.0105
    name:
  DeAc_Anh:
    mass: -62.0368
    name:
  Decay:
    mass: -203.0793
    name:
  Sodium:
    mass: 21.9819
    name: Na+
  Potassium:
    mass: 37.9559
    name: K+
  Nude:
    mass: 478.1799
    name: gm-
  Amidated:
    mass: -0.9840
    name: Amidated
  Amidase Product:
    mass: -480.1955
    name: (Amidase Product)
  Lactyl:
    mass: -408.1744
    name: (Lactyl)

mass_to_clean:
  sodiated:
    parent: ^gm|^m|^Lac
    target: ^Na+
  potassated:
    parent: ^gm|^m|^Lac
    target: ^K+
  decay:
    parent: ^gm
    target: ^m
