name: pgfinder
channels:
  - defaults
  - conda-forge
dependencies:
  # install dependencies
  - python=3.7
  - pandas
  - sqlite=3.32.3
  - numpy
  - jupyterlab
  - ipywidgets
  - ipysheet
  - openpyxl
