name: Run end-to-end tests

on:
  pull_request:
  push:
    branches: 'master'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: 'web/pnpm-lock.yaml'

      - name: Install Project Dependencies
        run: pnpm install

      - name: Install Playwright Browsers & Dependencies
        run: pnpx playwright install --with-deps

      - name: Run Playwright Tests
        run: pnpm test

      - name: Upload Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: /
          retention-days: 30
