name: Run library tests

on:
  pull_request:
  push:
    branches: 'master'

jobs:
  test:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.9", "3.10", "3.11"]
    defaults:
      run:
        working-directory: ./lib
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -e .
          pip install -e .[tests,pypi]
      - name: Test with pytest
        run: |
          pytest --cov=pgfinder
      - name: Determine coverage
        run: |
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
      - name: Checking CLI entry-point works
        run: |
          pip install -e .
          find_pg --config pgfinder/default_config.yaml
